# Reusable base settings (DRY via anchors)
x-trainer-common: &trainer-common
  build:
    context: ..
    dockerfile: docker/Dockerfile
    args:
      BASE_IMAGE: ${BASE_IMAGE-}   # optional override at build time
  image: rlds-trainer:latest
  working_dir: /app
  # Enable GPU in local docker compose (not swarm)
  gpus: all
  deploy:
    resources:
      reservations:
        devices:
          - capabilities: ["gpu"]
  # local Docker (not Swarm) can also use: gpus: all
  volumes:
    - ../:/app
    - ../outputs:/app/outputs
  environment:
    - WANDB_MODE=${WANDB_MODE:-online}
    - WANDB_API_KEY=${WANDB_API_KEY:-}
    - MUJOCO_GL=egl
    - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-all}
    - NVIDIA_DRIVER_CAPABILITIES=${NVIDIA_DRIVER_CAPABILITIES:-all}

services:

  # TRAIN service (default)
  trainer:
    <<: *trainer-common
    # Default runs your selected exp from config/defaults.yaml
    command: ["python", "scripts/train.py"]

  # (Optional) define a SEARCH profile you can enable later
  # For now it's just a TODO placeholder—no Optuna wiring yet.
  search:
    <<: *trainer-common
    profiles: ["search"]
    command: ["python", "scripts/search.py", "-m", "+hpo=optuna", "+hpo.space=ppo_basic"]
