package: _global_
defaults:
  - /trainer: bc
  - /dataset: minari
  - /model: mlp_gauss
  - /loss: bc_gaussian_nll
  - /optimizer: adamw
  - /evaluator: default_eval
  - _self_

exp:
  name: "quick_debug_bc"

dataset:
  path: "data/fetchreach_v2_expert_bc_v1"
  batch_size: 32
  num_workers: 2

trainer:
  max_steps: 1000
  eval_every: 200
  save_every: 500

